language: node.js
node_js:
  - "node"

sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build

after_success:
  - docker build -t cinerium .
  - docker run cinerium npm run test -- --coverage
