version: "3.7"

services:
  cinerium:
    container_name: cinerium
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 1337:80
    environment:
      - CHOKIDAR_USEPOLLING=true
